export const designState = {
  memberType: null,
  section: null,
  material: null,
  designMethod: null,
  designCode: null,
  lengthUnit: null,
  memberLength: null,
  unbracedLengthX: null,
  unbracedLengthY: null,
  unbracedLengthTop: null,
  unbracedLengthBot: null,
  Kx: null,
  Ky: null,
  Kz: null,
  Cb: null,
  loadPu: null,
  loadVux: null,
  loadVuy: null,
  loadMux: null,
  loadMuy: null,
  loadTu: null,
  seismicEnabled: false,
  seismicParams: null
};
